#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jul 12 21:39:55 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
